name: baikalc test

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install toolchain and runtime
        run: |
          sudo apt-get -y update
          sudo apt-get -y install make gcc-riscv64-linux-gnu qemu-user-static
      - name: build baikalc 
        working-directory: ./compiler
        run: make
      - name: run test # assumes python3 is installed. will fix if needed
        working-directory: ./compiler
        run: make test